### ISSUE TITLE
how does one transfer glasses style to output image?

### ISSUE THREAD

**Issue by luke-momentusresearch** [ToTheBeginning/PuLID#108]
First off, thank you for creating this model. I been trying out the samples on https://huggingface.co/spaces/yanze/PuLID-FLUX and locally and while the results are really good, I notice glasses are not included in the output image more often than not. I did not change any cfg or timestep settings. 

What should I do to fix this? Thanks

**Comment by ToTheBeginning** [comment]
We have noticed this issue. Technically, the reason for the loss of glasses probability is due to the introduction of ID loss, as accessories like glasses are not crucial for ID similarity. A temporary solution you could try is using different seeds or adding glasses to the prompt.
