### ISSUE TITLE
where are the models being downloaded?

### ISSUE THREAD

**Issue by fahadshery** [ToTheBeginning/PuLID#111]
I am dockerising this App,

It's annoying that it starts downloading models every time I rebuild. 

Where are these models being downloaded on disk?
I could simply download once and then map the folder within container.

Cheers

**Comment by ToTheBeginning** [comment]
Some models have been downloaded into the cache folder (for example, in the directories specified by the HF_HOME and TRANSFORMERS_CACHE environment variables), while others are specified to be downloaded in the models folder.
