### ISSUE TITLE
How to tell pulid to insert the face on a specific character if the image contain multiple people?

### ISSUE THREAD

**Issue by ClothingAI** [ToTheBeginning/PuLID#127]
Lets say i want to create an image with 2 people, a man talking to a woman.
And want to insert a face to the man.
What can i do to make sure it goes like that?
And prevent the woman from getting the man face?

**Comment by ToTheBeginning** [comment]
You may need the comfyui version of PuLID, which has attention-mask to support this

**Comment by ClothingAI** [comment]
> You may need the comfyui version of PuLID, which has attention-mask to support this

I was not able to make it work on comfy :'( (for some reason)

**Comment by katarzynasornat** [comment]
@ToTheBeginning is there any support for diffusers for attention mask to swap only one chosen face?

**Comment by Swarzox** [comment]
Looking for the same
