### ISSUE TITLE
Will PULID SDXL 1.1 be released as scheduled?

### ISSUE THREAD

**Issue by streamize** [ToTheBeginning/PuLID#136]
Hello, will PULID SDXL 1.1 be released soon as stated in the readme.md? I'm a fan of PULID technology, and I've been waiting for PULID SDXL 1.1 to be released since June this year. Is there going to be another delay?

**Comment by ToTheBeginning** [comment]
PuLID-v1.1 for SDXL and PuLID-FLUX-v0.9.1 have been release now. Thanks for your waiting and patience.

**Comment by streamize** [comment]
@ToTheBeginning Thank you!
