### ISSUE TITLE
why converting the align_face to grey scale?

### ISSUE THREAD

**Issue by 18445864529** [ToTheBeginning/PuLID#138]
and will it be problematic if you still use the RGB scale mean and std for normalizing the grey-scale image? which results in kinda high contrast dark blue faces before passing to eva-clip.

Thanks in advance for any discussions.

**Comment by ToTheBeginning** [comment]
We explained your first question at https://github.com/ToTheBeginning/PuLID/issues/98. For the second question, I think it is ok.
