### ISSUE TITLE
4 Steps lightning models.

### ISSUE THREAD

**Issue by Hany1978** [ToTheBeginning/PuLID#140]
Why in this update you didn't use 4 steps lightning model? and can I use any SDXL Lightning model?

**Comment by ToTheBeginning** [comment]
The v1.1 model supports both accelerated and non-accelerated models, as demonstrated in our [examples](https://github.com/ToTheBeginning/PuLID/blob/main/docs/pulid_v1.1.md). We have shown the results on the [dreamshaper-xl-lightning](https://civitai.com/models/112902?modelVersionId=354657), an accelerated model, as well as on the [Juggernaut-XL](https://civitai.com/models/133005?modelVersionId=348913), a non-accelerated model. However, if you intend to use the specific [SDXL-Lightning](https://huggingface.co/ByteDance/SDXL-Lightning) model, we still recommend using the v1 model.
