### ISSUE TITLE
How to modify code of old installation to tell it to use latest version of pulid? (What to modify in the app.py?)

### ISSUE THREAD

**Issue by ClothingAI** [ToTheBeginning/PuLID#144]
What to modify in the app.py please?
I want to use latest model but dont know how to tell the code to doit

**Comment by ToTheBeginning** [comment]
Maybe you need to pull and latest codes.

**Comment by ClothingAI** [comment]
> Maybe you need to pull and latest codes.

Indeed. but I modified the code (the UI) to get it to run more prompts at once. I hope it does not delete it. I guess I can make the changes back..
