### ISSUE TITLE
First Run and dont work! give error in the PulidFluxInsightFaceLoader Node!

### ISSUE THREAD

**Issue by merecesarchviz** [ToTheBeginning/PuLID#145]
I have the comfyui updated also the PuLID node! but when i run the example workflow o got this error:

any idea how to solve it?

![dfg](https://github.com/user-attachments/assets/011c57b1-7b2a-48f8-b119-8122b0c6c183)

**Comment by ToTheBeginning** [comment]
Please report this error to the maintainer of the ComfyUI implementation.
