### ISSUE TITLE
Info - related resources update

### ISSUE THREAD

**Issue by vladmandic** [ToTheBeginning/PuLID#149]
as per <https://github.com/ToTheBeginning/PuLID#paperclip-related-resources>
noting one more implementation: [sd.next](https://github.com/vladmandic/automatic/) as a built-in extension (with full credit given)
![pulid](https://github.com/user-attachments/assets/4b595e68-d388-4130-9a18-4949d15ac63b)

**Comment by ToTheBeginning** [comment]
Thank you very much for your contribution. I've noticed that PuLID is currently on the SD.Next dev branch. Could you please let me know when you plan to merge it into the main branch? Then I will add it to the related resources.

**Comment by vladmandic** [comment]
dev to master merge will likely be in few days as there are still few more things i want to complete.
regarding pulid - thanks for your work, results are really good.

i've went ahead and converted it to pure diffuser pipeline so it can be used with standard __call__ signature and with standard callbacks. as a result, it now works with realtime generate preview as well as compatible with other features like xyz grid, etc.

![image](https://github.com/user-attachments/assets/eb35506c-3705-40b2-969e-a60543aac7a4)

**Comment by ToTheBeginning** [comment]
Thanks again for your contribution! We have updated the related resources.
