### ISSUE TITLE
Potential VRAM Leak from facexlib and evaclip

### ISSUE THREAD

**Issue by huchenlei** [ToTheBeginning/PuLID#16]
I am trying to implement PuLID in A1111 here: https://github.com/Mikubill/sd-webui-controlnet/pull/2838

However, I found that the vram management of facexlib and evaclip is just very broken. In total they allocate about 3GB of vram and if you move their model to cpu, only about 1GB is freed. Another finding is that if you use really large image and directly pass it to facexlib, each time facexlib runs, the vram will increase significantly depending on input image size. I think this is a strong signal of vram leak. If you use small input files, the effect is probably unnoticeable.

Maybe I should file an issue in facexlib repo, but anyway just let people know.

**Comment by ToTheBeginning** [comment]
According to your description, this doesn't seem to be a memory leak. It's reasonable that the larger the input image sent into the network, the more memory it occupies. To avoid this, you can refer to [our current implementation](https://github.com/ToTheBeginning/PuLID/blob/main/app.py#L40) , i.e., resize the input image based on the longer side first.

**Comment by inspire-boy** [comment]
> I am trying to implement PuLID in A1111 here: [Mikubill/sd-webui-controlnet#2838](https://github.com/Mikubill/sd-webui-controlnet/pull/2838)
> 
> However, I found that the vram management of facexlib and evaclip is just very broken. In total they allocate about 3GB of vram and if you move their model to cpu, only about 1GB is freed. Another finding is that if you use really large image and directly pass it to facexlib, each time facexlib runs, the vram will increase significantly depending on input image size. I think this is a strong signal of vram leak. If you use small input files, the effect is probably unnoticeable.
> 
> Maybe I should file an issue in facexlib repo, but anyway just let people know.

if it have been solved? I saw some Vram Memory not free after task over on win10 platform.

**Comment by Lorian0** [comment]
I can confirm, the VRAM is not released after the generation task is completed

**Comment by huchenlei** [comment]
> According to your description, this doesn't seem to be a memory leak. It's reasonable that the larger the input image sent into the network, the more memory it occupies. To avoid this, you can refer to [our current implementation](https://github.com/ToTheBeginning/PuLID/blob/main/app.py#L40) , i.e., resize the input image based on the longer side first.

Resizing the input image does not solve the issue, it just make the issue look more unnoticable. Eventually after enough runs the leak will be apparent. Using a large image without resizing will make this leak easier to observe.

**Comment by ToTheBeginning** [comment]
Thanks for reporting the issue, we will investigate the BUG, PR are also welcomed.

**Comment by inspire-boy** [comment]
Has anyone solved this problem? if repository has some bugs.Why not the problem show in this repository：https://huggingface.co/spaces/yanze/PuLID

I found It work well in this diffusers project but webui. in ip-adapter, 24GB is not enough. 
here is my test picture：
 
![微信图片_20240507155932](https://github.com/ToTheBeginning/PuLID/assets/112338987/45bd53b5-af5d-4a20-b67c-0397dac1c825)

Hope someone can give some advice.

**Comment by huchenlei** [comment]
Let me inspect what I am doing wrong comparing to this repo.

**Comment by huchenlei** [comment]
Transfering the issue to https://github.com/Mikubill/sd-webui-controlnet
