### ISSUE TITLE
Please 'pip install apex'

### ISSUE THREAD

**Issue by Orenji-Tangerine** [ToTheBeginning/PuLID#56]
I got a prompt please 'pip install apex' on the console screen, but this PuLID runs fine without this on ComfyUI. I then proceed to install this Apex (Im using Windows), via python setup.py install after git clone this Apex. The previous warning about installing Apex is gone but PuLID cannot run after this and specifically got this warning: [No module named 'fused_layer_norm_cuda'] on my ComfyUI console. The Pytorch is 2.1.2 + CU 11.8.

I rolled back by uninstalling Apex, and PuLID works again. Im just wondering if a proper Apex actually speeds up the process? If yes, which version shall I install and how shall I do? Im not that tech-savvy and am just an average SD user. Please help... Thanks in advance.

**Comment by AlexTang0417** [comment]
Install the CUDA version using the --cuda_ext --cpp_ext command.
