### ISSUE TITLE
 KeyError 'img_in.weight._data' on run with --offload --fp8

### ISSUE THREAD

**Issue by heinrichI** [ToTheBeginning/PuLID#69]
![image](https://github.com/user-attachments/assets/b449438b-dd2f-4e59-b267-c2bfead68c8c)
 KeyError
'img_in.weight._data'
  File "I:\flux\PuLID\flux\util.py", line 158, in load_flow_model_quintized
    requantize(model, sd, quantization_map, device=device)
  File "I:\flux\PuLID\app_flux.py", line 25, in get_models
    model = load_flow_model_quintized(name, device="cpu" if offload else device)
  File "I:\flux\PuLID\app_flux.py", line 39, in __init__
    self.model, self.ae, self.t5, self.clip = get_models(
  File "I:\flux\PuLID\app_flux.py", line 197, in create_demo
    generator = FluxGenerator(model_name, device, offload, aggressive_offload, args)
  File "I:\flux\PuLID\app_flux.py", line 325, in <module>
    demo = create_demo(args, args.name, args.device, args.offload, args.aggressive_offload)
KeyError: 'img_in.weight._data'

optimum-quanto==0.2.4
torch==2.4.1+cu121
torchvision==0.19.1+cu121

In ckpt_path I load unet/flux1-dev-fp8.safetensors

**Comment by ToTheBeginning** [comment]
We use flux-fp8 checkpoint from https://huggingface.co/XLabs-AI/flux-dev-fp8 (it will be automatically downloaded), please check if you are using the same model. We also update the readme to make it more clear.

**Comment by smthemex** [comment]
I also encountered an error when loading the X_lab model and its accompanying config file. Instead, I changed it to other unet and unet config files, and it run successfully. The following is a picture of the success:
![flux_pulid_fp8_12GVR](https://github.com/user-attachments/assets/1b487c85-2a18-4f83-a493-61b4c0628076)

**Comment by ToTheBeginning** [comment]
> I also encountered an error when loading the X_lab model and its accompanying config file. Instead, I changed it to other unet and unet config files, and it run successfully. The following is a picture of the success: ![flux_pulid_fp8_12GVR](https://private-user-images.githubusercontent.com/138738845/367557883-1b487c85-2a18-4f83-a493-61b4c0628076.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjYzNzI2NDUsIm5iZiI6MTcyNjM3MjM0NSwicGF0aCI6Ii8xMzg3Mzg4NDUvMzY3NTU3ODgzLTFiNDg3Yzg1LTJhMTgtNGY4My1hNDkzLTYxYjRjMDYyODA3Ni5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTE1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkxNVQwMzUyMjVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xYTc5ZjFhODQ1ZGEzYzYzODAxNjkxYmY1OWQyZDUxZTEyZTVmMzBhMWM2MjE4ODhkZGY5Y2RiODkzY2Y0NzM1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.rUTbBzjm0Ajj5nRMQnTNxkhk0aBoQtLorm3WdfgIdVk)

This does not look like PuLID-FLUX. As far as we know, the porting to comfyui is still in develop.

**Comment by smthemex** [comment]
> > I also encountered an error when loading the X_lab model and its accompanying config file. Instead, I changed it to other unet and unet config files, and it run successfully. The following is a picture of the success: ![flux_pulid_fp8_12GVR](https://private-user-images.githubusercontent.com/138738845/367557883-1b487c85-2a18-4f83-a493-61b4c0628076.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjYzNzI2NDUsIm5iZiI6MTcyNjM3MjM0NSwicGF0aCI6Ii8xMzg3Mzg4NDUvMzY3NTU3ODgzLTFiNDg3Yzg1LTJhMTgtNGY4My1hNDkzLTYxYjRjMDYyODA3Ni5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTE1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkxNVQwMzUyMjVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xYTc5ZjFhODQ1ZGEzYzYzODAxNjkxYmY1OWQyZDUxZTEyZTVmMzBhMWM2MjE4ODhkZGY5Y2RiODkzY2Y0NzM1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.rUTbBzjm0Ajj5nRMQnTNxkhk0aBoQtLorm3WdfgIdVk)
> 
> This does not look like PuLID-FLUX. As far as we know, the porting to comfyui is still in develop.

it working with PULID flux ,and run in 12 G VRAM

**Comment by heinrichI** [comment]
> [flux-dev-fp8](https://huggingface.co/XLabs-AI/flux-dev-fp8)

Yes I pass another flux-dev-fp8.safetensors, which weighed 16 GB. With the correct file it worked.
