### ISSUE TITLE
Server could not start up.

### ISSUE THREAD

**Issue by ultimatech-cn** [ToTheBeginning/PuLID#77]
It is fine yesterday.
But fail to start today, the error is like following

> 
> loading from pulid_ca
> loading from pulid_encoder
> Running on local URL:  http://0.0.0.0:8080
> Traceback (most recent call last):
>   File "D:\ProgramData\anaconda3\envs\pulid\lib\site-packages\httpx\_transports\default.py", line 72, in map_httpcore_exceptions
>     yield
>   File "D:\ProgramData\anaconda3\envs\pulid\lib\site-packages\httpx\_transports\default.py", line 236, in handle_request
>     resp = self._pool.handle_request(req)
>   File "D:\ProgramData\anaconda3\envs\pulid\lib\site-packages\httpcore\_sync\connection_pool.py", line 216, in handle_request
>     raise exc from None
>   File "D:\ProgramData\anaconda3\envs\pulid\lib\site-packages\httpcore\_sync\connection_pool.py", line 196, in handle_request
>     response = connection.handle_request(
>   File "D:\ProgramData\anaconda3\envs\pulid\lib\site-packages\httpcore\_sync\http_proxy.py", line 207, in handle_request
>     return self._connection.handle_request(proxy_request)
>   File "D:\ProgramData\anaconda3\envs\pulid\lib\site-packages\httpcore\_sync\connection.py", line 101, in handle_request
>     return self._connection.handle_request(request)
>   File "D:\ProgramData\anaconda3\envs\pulid\lib\site-packages\httpcore\_sync\http11.py", line 143, in handle_request
>     raise exc
>   File "D:\ProgramData\anaconda3\envs\pulid\lib\site-packages\httpcore\_sync\http11.py", line 113, in handle_request
>     ) = self._receive_response_headers(**kwargs)
>   File "D:\ProgramData\anaconda3\envs\pulid\lib\site-packages\httpcore\_sync\http11.py", line 186, in _receive_response_headers
>     event = self._receive_event(timeout=timeout)
>   File "D:\ProgramData\anaconda3\envs\pulid\lib\site-packages\httpcore\_sync\http11.py", line 238, in _receive_event
>     raise RemoteProtocolError(msg)
> httpcore.RemoteProtocolError: Server disconnected without sending a response.
> 
> The above exception was the direct cause of the following exception:
> 
> Traceback (most recent call last):
>   File "F:\dev\PuLID\app_flux.py", line 311, in <module>
>     demo.launch(server_name='0.0.0.0', server_port=7860, share=True)
>   File "D:\ProgramData\anaconda3\envs\pulid\lib\site-packages\gradio\blocks.py", line 2254, in launch
>     httpx.get(
>   File "D:\ProgramData\anaconda3\envs\pulid\lib\site-packages\httpx\_api.py", line 210, in get
>     return request(
>   File "D:\ProgramData\anaconda3\envs\pulid\lib\site-packages\httpx\_api.py", line 118, in request
>     return client.request(
>   File "D:\ProgramData\anaconda3\envs\pulid\lib\site-packages\httpx\_client.py", line 837, in request
>     return self.send(request, auth=auth, follow_redirects=follow_redirects)
>   File "D:\ProgramData\anaconda3\envs\pulid\lib\site-packages\httpx\_client.py", line 926, in send
>     response = self._send_handling_auth(
>   File "D:\ProgramData\anaconda3\envs\pulid\lib\site-packages\httpx\_client.py", line 954, in _send_handling_auth
>     response = self._send_handling_redirects(
>   File "D:\ProgramData\anaconda3\envs\pulid\lib\site-packages\httpx\_client.py", line 991, in _send_handling_redirects
>     response = self._send_single_request(request)
>   File "D:\ProgramData\anaconda3\envs\pulid\lib\site-packages\httpx\_client.py", line 1027, in _send_single_request
>     response = transport.handle_request(request)
>   File "D:\ProgramData\anaconda3\envs\pulid\lib\site-packages\httpx\_transports\default.py", line 235, in handle_request
>     with map_httpcore_exceptions():
>   File "D:\ProgramData\anaconda3\envs\pulid\lib\contextlib.py", line 153, in __exit__
>     self.gen.throw(typ, value, traceback)
>   File "D:\ProgramData\anaconda3\envs\pulid\lib\site-packages\httpx\_transports\default.py", line 89, in map_httpcore_exceptions
>     raise mapped_exc(message) from exc
> httpx.RemoteProtocolError: Server disconnected without sending a response.

Any idea about it?

**Comment by ToTheBeginning** [comment]
maybe you can reinstall httpx to a lower version (like 0.23.3 in our requirements)

**Comment by ultimatech-cn** [comment]
Thanks a lot for kind reply.
It works.
