### ISSUE TITLE
How to run img2img

### ISSUE THREAD

**Issue by mamicro-li** [ToTheBeginning/PuLID#80]

**Comment by Roweguy** [comment]
>

**Comment by Roweguy** [comment]
Good

**Comment by ToTheBeginning** [comment]
> Is there any other repo that has implemented FLUX img2img so I can refer to.

You can refer to https://github.com/black-forest-labs/flux/blob/main/demo_gr.py#L71

**Comment by mamicro-li** [comment]
> > Is there any other repo that has implemented FLUX img2img so I can refer to.
> 
> @mamicro-li You can refer to https://github.com/black-forest-labs/flux/blob/main/demo_gr.py#L71

Thanks for your sharing! I have tried that code but it keeps generating foggy and blurry image which looks like a white filter is added on the original image. I run the vanilla img2img demo w/o pulid as well. It has the same problem. Is it normal or is there any problem with my setting?

**Comment by mamicro-li** [comment]
> > > > Is there any other repo that has implemented FLUX img2img so I can refer to.
> > > 
> > > 
> > > @mamicro-li You can refer to https://github.com/black-forest-labs/flux/blob/main/demo_gr.py#L71
> > 
> > 
> > Thanks for your sharing! I have tried that code but it keeps generating foggy and blurry image which looks like a white filter is added on the original image. I run the vanilla img2img demo w/o pulid as well. It has the same problem. Is it normal or is there any problem with my setting?
> 
> Seems like the gradio demo from BFL has a BUG about vae range, it should be [-1, 1], but they are using [0, 1]

In ComfyUI's flux pipeline, the pixel range is normalized to [0, 1] before VAE as well. Not sure if it is the key error. BTW, diffusers now has a good support on FLUX. Are you planning to reorg the code based on diffusers?

**Comment by smthemex** [comment]
The latest version of diffuser already supports Flux img2img's pipe process

**Comment by mamicro-li** [comment]
Difffusers works fine with PuLID without any bug.

**Comment by easonhyx** [comment]
> Diffusers works fine with Flux-PuLID without any bug.

hello guy, have you run the Flux-PuLID pipeline by diffusers? how to make it?
