### ISSUE TITLE
How did you train the FLUX model?

### ISSUE THREAD

**Issue by jianzongwu** [ToTheBeginning/PuLID#94]
Do you use Lora, or train the whole parameters?

What machines do you use to avoid OOM?

**Comment by ToTheBeginning** [comment]
We use A100-80G with zero2

**Comment by jianzongwu** [comment]
Got it.

Do you train LoRA, or all the weights in FLUX?

And how many GPUs, total batch_size do you use to avoid OOM?


Thanks a lot for contributing to the FLUX training community!

**Comment by ToTheBeginning** [comment]
As simply described in the [Technical Details](https://github.com/ToTheBeginning/PuLID/blob/main/docs/pulid_for_flux.md#some-technical-details), we train additional adapters. We utilized 8-24 A100 GPUs, and the batch size per gpu could be set to 4 during the first stage.

**Comment by yooj-lee** [comment]
@ToTheBeginning Hi, thanks for informing us and one more question pls if you don't mind! Just to confirm, would training PuLID-Flux work effectively with 8 A100 GPUs, or is it highly recommended to scale up to 24 GPUs for acceptable results? Your guidance would be much appreciated! Also, still looking forward to the training code release :)
