### ISSUE TITLE
please help!  Request ID: Root=....

### ISSUE THREAD

**Issue by yangnt** [ToTheBeginning/PuLID#97]
Sorry, the following happened to me again, please help!
raise _format(GatedRepoError, message, response) from e
huggingface_hub.errors.GatedRepoError: 401 Client Error. (Request ID: Root=1-66f4b037-1bf3d7d219afbc904ee05694;5601d2c9-8fd8-4ed8-b38d-d8a432e1fa59)

Cannot access gated repo for url https://huggingface.co/black-forest-labs/FLUX.1-dev/resolve/main/ae.safetensors.
Access to model black-forest-labs/FLUX.1-dev is restricted. You must have access to it and be authenticated to access it. Please log in.

**Comment by ToTheBeginning** [comment]
You need to apply FLUX.1-dev access first in https://huggingface.co/black-forest-labs/FLUX.1-dev
